### ISSUE TITLE
Unable to use Numismatics beyond 1.0.4

### ISSUE THREAD

**Issue by Underplayer97** [snackbag-net/Create-Coins-Arise#1]
Create: Coins Arise gives an error to Fabric requiring version "1.0.4+fabric-mc1.20.1" of Create: Numismatics. This can prove to be an issue when Numismatics are on "1.0.6+fabric-mc1.20.1" A fix that you can do to allow versions beyond 1.0.4 is setting in your fabric.mod.json dependencies to have ">=" in the required version. For example requiring 1.0.4 and beyond of Numismatics would have the required version of ">=1.0.4+fabric-mc1.20.1" in the dependency list.

**Comment by JXSnack** [comment]
Will fix in 1.0.1. Estimated release is in 3-4 hours

**Comment by Underplayer97** [comment]
Okay, thank you

**Comment by CassieRoseZA** [comment]
Waiting for a release

**Comment by JXSnack** [comment]
Released on Modrinth and Github
